name: CICD

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::758225243696:role/github-actions-deploy-role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag & push image
        id: build-image
        env:
          ECR_REGISTRY: 758225243696.dkr.ecr.ap-south-1.amazonaws.com
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY: nodejs-app
        run: |
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # - name: Render ECS task definition
      #   id: taskdef
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: nodejs-app-task-definition.json
      #     container-name: nodejs-app
      #     image: ${{ steps.build-image.outputs.image }}

      # - name: Deploy to ECS
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: ${{ steps.taskdef.outputs.task-definition }}
      #     service: odejs-app-service
      #     cluster: DevCluster
      #     wait-for-service-stability: true
