name: CICD

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.CICD_ROLE_ARN }}
          aws-region: ${{ secrets.CICD_AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag & push image
        id: build-image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.CICD_AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.CICD_AWS_REGION }}
          REPOSITORY: ${{ secrets.CICD_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT


      # - name: Render ECS task definition
      #   id: taskdef
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: nodejs-app-task-definition.json
      #     container-name: nodejs-app
      #     image: ${{ steps.build-image.outputs.image }}

      # - name: Deploy to ECS
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: ${{ steps.taskdef.outputs.task-definition }}
      #     service: odejs-app-service
      #     cluster: DevCluster
      #     wait-for-service-stability: true
